// Generated by https://quicktype.io
/* comienzo traer todos los actores  */
export interface AllActors {
    data: Actor[];
    msg:  string;
}

export interface Actor {
    id:                number;
    first_name:        string;
    last_name:         string;
    rating:            string;
    favorite_movie_id: number | null;
    createdAt:         null;
    updatedAt:         null;
}
/* fin traer todos los actores  */

/* comienzo traer un solo actor */

export interface ActorDetailByID {
    data: ActorWithInclude;
    msg:  string;
}

export interface ActorWithInclude extends Actor {
    movies: ActorsMovies[];
}
export interface ActorsMovies {
    id:           number;
    title:        string;
    rating:       string;
    awards:       number;
    release_date: string;
    length:       number;
    genre_id:     number;
    createdAt:    null;
    updatedAt:    null;
    actor_movie:  Actor_Movie;
}

export interface Actor_Movie {
    actorId:   number;
    movieId:   number;
    createdAt: null;
    updatedAt: null;
}

/* fin traer un solo actor */