// Generated by https://quicktype.io

export interface AllGeneros {
    data: Genero[];
    msg:  string;
}

export interface Genero {
    id:        number;
    name:      string;
    ranking:   number;
    active:    number;
    createdAt: string;
    updatedAt: null;
}
